// <auto-generated />
using System;
using EF_SGBM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EF_SGBM.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20260213024426_InicialSeed")]
    partial class InicialSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entidades_SGBM.Cajas", b =>
                {
                    b.Property<int?>("IdCaja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdCaja"));

                    b.Property<bool>("Abierta")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HoraCierre")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdTipo")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalEfectivo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("TotalMP")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdCaja");

                    b.HasIndex("IdTipo");

                    b.ToTable("Cajas");
                });

            modelBuilder.Entity("Entidades_SGBM.Categorias", b =>
                {
                    b.Property<int?>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdCategoria"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Indole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Entidades_SGBM.Clientes", b =>
                {
                    b.Property<int?>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdCliente"));

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<bool>("esMiembro")
                        .HasColumnType("bit");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPersona");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Entidades_SGBM.Contactos", b =>
                {
                    b.Property<int?>("IdContacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdContacto"));

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("ExtranjeroWhatsapp")
                        .HasColumnType("bit");

                    b.Property<string>("Facebook")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("IdPersona")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Instagram")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Whatsapp")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("IdContacto");

                    b.HasIndex("IdPersona");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("Entidades_SGBM.CostosServicios", b =>
                {
                    b.Property<int?>("IdCostoServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdCostoServicio"));

                    b.Property<decimal?>("CantidadMedida")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int?>("Unidades")
                        .HasColumnType("int");

                    b.HasKey("IdCostoServicio");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdServicio");

                    b.ToTable("CostosServicios");
                });

            modelBuilder.Entity("Entidades_SGBM.Credenciales", b =>
                {
                    b.Property<int?>("IdCredencial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdCredencial"));

                    b.Property<string>("Accesos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.HasKey("IdCredencial");

                    b.HasIndex("IdNivel");

                    b.ToTable("Credenciales");
                });

            modelBuilder.Entity("Entidades_SGBM.DetallesFacturas", b =>
                {
                    b.Property<int?>("IdDetalleFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdDetalleFactura"));

                    b.Property<int>("IdDetalleVenta")
                        .HasColumnType("int");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleFactura");

                    b.HasIndex("IdDetalleVenta");

                    b.HasIndex("IdFactura");

                    b.ToTable("DetallesFacturas");
                });

            modelBuilder.Entity("Entidades_SGBM.DetallesVentas", b =>
                {
                    b.Property<int?>("IdDetalleVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdDetalleVenta"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdFondoMembresia")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("IdServicio")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<decimal?>("InteresDescuento")
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("PrecioUnitario")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdDetalleVenta");

                    b.HasIndex("IdProducto");

                    b.HasIndex("IdServicio");

                    b.HasIndex("IdVenta");

                    b.ToTable("DetallesVentas");
                });

            modelBuilder.Entity("Entidades_SGBM.Domicilios", b =>
                {
                    b.Property<int?>("IdDomicilio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdDomicilio"));

                    b.Property<string>("Altura")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Barrio")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Calle")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Depto")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("IdLocalidad")
                        .HasColumnType("int");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<string>("Piso")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdDomicilio");

                    b.HasIndex("IdLocalidad");

                    b.HasIndex("IdProveedor");

                    b.ToTable("Domicilios");
                });

            modelBuilder.Entity("Entidades_SGBM.Empleados", b =>
                {
                    b.Property<int?>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdEmpleado"));

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdPersona")
                        .HasColumnType("int");

                    b.Property<string>("TipoEmpleado")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdPersona");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("Entidades_SGBM.Estados", b =>
                {
                    b.Property<int?>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdEstado"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Indole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdEstado");

                    b.ToTable("Estados");

                    b.HasData(
                        new
                        {
                            IdEstado = 1,
                            Estado = "Activo",
                            Indole = "Empleados"
                        },
                        new
                        {
                            IdEstado = 2,
                            Estado = "Inactivo",
                            Indole = "Empleados"
                        },
                        new
                        {
                            IdEstado = 3,
                            Estado = "Bloqueado",
                            Indole = "Empleados"
                        },
                        new
                        {
                            IdEstado = 4,
                            Estado = "Desvinculado",
                            Indole = "Empleados"
                        },
                        new
                        {
                            IdEstado = 5,
                            Estado = "Activo",
                            Indole = "Clientes"
                        },
                        new
                        {
                            IdEstado = 6,
                            Estado = "Inactivo",
                            Indole = "Clientes"
                        },
                        new
                        {
                            IdEstado = 7,
                            Estado = "Activo",
                            Indole = "Servicios"
                        },
                        new
                        {
                            IdEstado = 8,
                            Estado = "Inactivo",
                            Indole = "Servicios"
                        },
                        new
                        {
                            IdEstado = 9,
                            Estado = "En Curso",
                            Indole = "Ventas"
                        },
                        new
                        {
                            IdEstado = 10,
                            Estado = "Finalizada",
                            Indole = "Ventas"
                        },
                        new
                        {
                            IdEstado = 11,
                            Estado = "Anulada",
                            Indole = "Ventas"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.Facturas", b =>
                {
                    b.Property<int?>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdFactura"));

                    b.Property<int>("IdMedioPago")
                        .HasColumnType("int");

                    b.Property<int?>("IdTransaccion")
                        .HasColumnType("int");

                    b.Property<int>("IdVenta")
                        .HasColumnType("int");

                    b.Property<string>("NroFactura")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("TotalAbonado")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdMedioPago");

                    b.HasIndex("IdTransaccion");

                    b.HasIndex("IdVenta");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Entidades_SGBM.Localidades", b =>
                {
                    b.Property<int>("IdLocalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLocalidad"));

                    b.Property<string>("CodPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProvincia")
                        .HasColumnType("int");

                    b.Property<string>("Localidad")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdLocalidad");

                    b.HasIndex("IdProvincia");

                    b.ToTable("Localidades");

                    b.HasData(
                        new
                        {
                            IdLocalidad = 1,
                            CodPostal = "2820",
                            IdProvincia = 1,
                            Localidad = "Gualeguaychú"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.MediosPagos", b =>
                {
                    b.Property<int?>("IdMedioPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdMedioPago"));

                    b.Property<string>("Medio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdMedioPago");

                    b.ToTable("MediosPagos");
                });

            modelBuilder.Entity("Entidades_SGBM.Niveles", b =>
                {
                    b.Property<int?>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdNivel"));

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdNivel");

                    b.ToTable("Niveles");

                    b.HasData(
                        new
                        {
                            IdNivel = 1,
                            Nivel = "Admin"
                        },
                        new
                        {
                            IdNivel = 2,
                            Nivel = "Propietario"
                        },
                        new
                        {
                            IdNivel = 3,
                            Nivel = "Responsable"
                        },
                        new
                        {
                            IdNivel = 4,
                            Nivel = "Barbero"
                        },
                        new
                        {
                            IdNivel = 5,
                            Nivel = "Invitado"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.Personas", b =>
                {
                    b.Property<int?>("IdPersona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdPersona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("FechaNac")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdDomicilio")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdPersona");

                    b.HasIndex("IdDomicilio");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Entidades_SGBM.Productos", b =>
                {
                    b.Property<int?>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdProducto"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<decimal?>("CantidadMedida")
                        .HasColumnType("decimal(10,4)");

                    b.Property<string>("CodProducto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Comision")
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("Costo")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("IdUnidadMedida")
                        .HasColumnType("int");

                    b.Property<int?>("Medida")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int?>("idCategoria")
                        .HasColumnType("int");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("IdUnidadMedida");

                    b.HasIndex("idCategoria");

                    b.ToTable("Productos");
                });

            modelBuilder.Entity("Entidades_SGBM.Proveedores", b =>
                {
                    b.Property<int?>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdProveedor"));

                    b.Property<string>("Cuit")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdProveedor");

                    b.ToTable("Proveedores");
                });

            modelBuilder.Entity("Entidades_SGBM.Provincias", b =>
                {
                    b.Property<int>("IdProvincia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProvincia"));

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdProvincia");

                    b.ToTable("Provincias");

                    b.HasData(
                        new
                        {
                            IdProvincia = 1,
                            Provincia = "Entre Ríos"
                        },
                        new
                        {
                            IdProvincia = 2,
                            Provincia = "Buenos Aires"
                        },
                        new
                        {
                            IdProvincia = 3,
                            Provincia = "Catamarca"
                        },
                        new
                        {
                            IdProvincia = 4,
                            Provincia = "Chaco"
                        },
                        new
                        {
                            IdProvincia = 5,
                            Provincia = "Chubut"
                        },
                        new
                        {
                            IdProvincia = 6,
                            Provincia = "Córdoba"
                        },
                        new
                        {
                            IdProvincia = 7,
                            Provincia = "Corrientes"
                        },
                        new
                        {
                            IdProvincia = 8,
                            Provincia = "Formosa"
                        },
                        new
                        {
                            IdProvincia = 9,
                            Provincia = "Jujuy"
                        },
                        new
                        {
                            IdProvincia = 10,
                            Provincia = "La Pampa"
                        },
                        new
                        {
                            IdProvincia = 11,
                            Provincia = "La Rioja"
                        },
                        new
                        {
                            IdProvincia = 12,
                            Provincia = "Mendoza"
                        },
                        new
                        {
                            IdProvincia = 13,
                            Provincia = "Misiones"
                        },
                        new
                        {
                            IdProvincia = 14,
                            Provincia = "Neuquén"
                        },
                        new
                        {
                            IdProvincia = 15,
                            Provincia = "Río Negro"
                        },
                        new
                        {
                            IdProvincia = 16,
                            Provincia = "Salta"
                        },
                        new
                        {
                            IdProvincia = 17,
                            Provincia = "San Juan"
                        },
                        new
                        {
                            IdProvincia = 18,
                            Provincia = "San Luis"
                        },
                        new
                        {
                            IdProvincia = 19,
                            Provincia = "Santa Cruz"
                        },
                        new
                        {
                            IdProvincia = 20,
                            Provincia = "Santa Fe"
                        },
                        new
                        {
                            IdProvincia = 21,
                            Provincia = "Santiago del Estero"
                        },
                        new
                        {
                            IdProvincia = 22,
                            Provincia = "Tierra del Fuego"
                        },
                        new
                        {
                            IdProvincia = 23,
                            Provincia = "Tucumán"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.Servicios", b =>
                {
                    b.Property<int?>("IdServicio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdServicio"));

                    b.Property<decimal>("Comision")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal>("Costos")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<decimal>("Margen")
                        .HasColumnType("decimal(12,2)");

                    b.Property<string>("NombreServicio")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("PrecioVenta")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("Puntaje")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.HasKey("IdServicio");

                    b.HasIndex("IdCategoria");

                    b.ToTable("Servicios");
                });

            modelBuilder.Entity("Entidades_SGBM.TiposCajas", b =>
                {
                    b.Property<int>("IdTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipo"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipo");

                    b.ToTable("TiposCajas");

                    b.HasData(
                        new
                        {
                            IdTipo = 1,
                            Tipo = "Productos"
                        },
                        new
                        {
                            IdTipo = 2,
                            Tipo = "Servicios"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.TiposTransacciones", b =>
                {
                    b.Property<int?>("IdTipoTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTipoTransaccion"));

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdTipoTransaccion");

                    b.ToTable("TiposTransacciones");
                });

            modelBuilder.Entity("Entidades_SGBM.Transacciones", b =>
                {
                    b.Property<int?>("IdTransaccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdTransaccion"));

                    b.Property<DateTime>("Hora")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCaja")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoTransaccion")
                        .HasColumnType("int");

                    b.Property<decimal?>("MontoEgreso")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("MontoIngreso")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdTransaccion");

                    b.HasIndex("IdCaja");

                    b.HasIndex("IdTipoTransaccion");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("Entidades_SGBM.UnidadesMedidas", b =>
                {
                    b.Property<int?>("IdUnidadMedida")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdUnidadMedida"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Unidad")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdUnidadMedida");

                    b.ToTable("UnidadesMedidas");

                    b.HasData(
                        new
                        {
                            IdUnidadMedida = 1,
                            Descripcion = "Gramos",
                            Unidad = "gr"
                        },
                        new
                        {
                            IdUnidadMedida = 2,
                            Descripcion = "Mililitros",
                            Unidad = "ml"
                        },
                        new
                        {
                            IdUnidadMedida = 3,
                            Descripcion = "Centímetros Cúbicos",
                            Unidad = "cc"
                        },
                        new
                        {
                            IdUnidadMedida = 4,
                            Descripcion = "Litros",
                            Unidad = "lt"
                        });
                });

            modelBuilder.Entity("Entidades_SGBM.Usuarios", b =>
                {
                    b.Property<int?>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdUsuario"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<string>("Imagen")
                        .HasMaxLength(230)
                        .HasColumnType("nvarchar(230)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdNivel");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Entidades_SGBM.Ventas", b =>
                {
                    b.Property<int?>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("IdVenta"));

                    b.Property<DateTime>("FechaVenta")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<string>("NroVenta")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEstado");

                    b.ToTable("Ventas");
                });

            modelBuilder.Entity("Entidades_SGBM.Cajas", b =>
                {
                    b.HasOne("Entidades_SGBM.TiposCajas", "TiposCajas")
                        .WithMany()
                        .HasForeignKey("IdTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TiposCajas");
                });

            modelBuilder.Entity("Entidades_SGBM.Clientes", b =>
                {
                    b.HasOne("Entidades_SGBM.Estados", "Estados")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Personas", "Personas")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estados");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Entidades_SGBM.Contactos", b =>
                {
                    b.HasOne("Entidades_SGBM.Personas", "Personas")
                        .WithMany()
                        .HasForeignKey("IdPersona");

                    b.HasOne("Entidades_SGBM.Proveedores", "Proveedores")
                        .WithMany()
                        .HasForeignKey("IdProveedor");

                    b.Navigation("Personas");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Entidades_SGBM.CostosServicios", b =>
                {
                    b.HasOne("Entidades_SGBM.Productos", "Productos")
                        .WithMany()
                        .HasForeignKey("IdProducto");

                    b.HasOne("Entidades_SGBM.Servicios", "Servicios")
                        .WithMany()
                        .HasForeignKey("IdServicio")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("Entidades_SGBM.Credenciales", b =>
                {
                    b.HasOne("Entidades_SGBM.Niveles", "Niveles")
                        .WithMany()
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("Entidades_SGBM.DetallesFacturas", b =>
                {
                    b.HasOne("Entidades_SGBM.DetallesVentas", "DetallesVentas")
                        .WithMany()
                        .HasForeignKey("IdDetalleVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Facturas", "Facturas")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DetallesVentas");

                    b.Navigation("Facturas");
                });

            modelBuilder.Entity("Entidades_SGBM.DetallesVentas", b =>
                {
                    b.HasOne("Entidades_SGBM.Productos", "Productos")
                        .WithMany()
                        .HasForeignKey("IdProducto");

                    b.HasOne("Entidades_SGBM.Servicios", "Servicios")
                        .WithMany()
                        .HasForeignKey("IdServicio");

                    b.HasOne("Entidades_SGBM.Ventas", "Ventas")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Productos");

                    b.Navigation("Servicios");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Entidades_SGBM.Domicilios", b =>
                {
                    b.HasOne("Entidades_SGBM.Localidades", "Localidades")
                        .WithMany()
                        .HasForeignKey("IdLocalidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Proveedores", "Proveedores")
                        .WithMany()
                        .HasForeignKey("IdProveedor");

                    b.Navigation("Localidades");

                    b.Navigation("Proveedores");
                });

            modelBuilder.Entity("Entidades_SGBM.Empleados", b =>
                {
                    b.HasOne("Entidades_SGBM.Estados", "Estados")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Personas", "Personas")
                        .WithMany()
                        .HasForeignKey("IdPersona")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estados");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("Entidades_SGBM.Facturas", b =>
                {
                    b.HasOne("Entidades_SGBM.MediosPagos", "MediosPagos")
                        .WithMany()
                        .HasForeignKey("IdMedioPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Transacciones", "Transacciones")
                        .WithMany()
                        .HasForeignKey("IdTransaccion");

                    b.HasOne("Entidades_SGBM.Ventas", "Ventas")
                        .WithMany()
                        .HasForeignKey("IdVenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MediosPagos");

                    b.Navigation("Transacciones");

                    b.Navigation("Ventas");
                });

            modelBuilder.Entity("Entidades_SGBM.Localidades", b =>
                {
                    b.HasOne("Entidades_SGBM.Provincias", "Provincias")
                        .WithMany()
                        .HasForeignKey("IdProvincia")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Provincias");
                });

            modelBuilder.Entity("Entidades_SGBM.Personas", b =>
                {
                    b.HasOne("Entidades_SGBM.Domicilios", "Domicilios")
                        .WithMany()
                        .HasForeignKey("IdDomicilio");

                    b.Navigation("Domicilios");
                });

            modelBuilder.Entity("Entidades_SGBM.Productos", b =>
                {
                    b.HasOne("Entidades_SGBM.Proveedores", "Proveedores")
                        .WithMany()
                        .HasForeignKey("IdProveedor");

                    b.HasOne("Entidades_SGBM.UnidadesMedidas", "UnidadesMedidas")
                        .WithMany()
                        .HasForeignKey("IdUnidadMedida");

                    b.HasOne("Entidades_SGBM.Categorias", "Categorias")
                        .WithMany()
                        .HasForeignKey("idCategoria");

                    b.Navigation("Categorias");

                    b.Navigation("Proveedores");

                    b.Navigation("UnidadesMedidas");
                });

            modelBuilder.Entity("Entidades_SGBM.Servicios", b =>
                {
                    b.HasOne("Entidades_SGBM.Categorias", "Categorias")
                        .WithMany()
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorias");
                });

            modelBuilder.Entity("Entidades_SGBM.Transacciones", b =>
                {
                    b.HasOne("Entidades_SGBM.Cajas", "Cajas")
                        .WithMany()
                        .HasForeignKey("IdCaja")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.TiposTransacciones", "TiposTransacciones")
                        .WithMany()
                        .HasForeignKey("IdTipoTransaccion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cajas");

                    b.Navigation("TiposTransacciones");
                });

            modelBuilder.Entity("Entidades_SGBM.Usuarios", b =>
                {
                    b.HasOne("Entidades_SGBM.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Niveles", "Niveles")
                        .WithMany()
                        .HasForeignKey("IdNivel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleados");

                    b.Navigation("Niveles");
                });

            modelBuilder.Entity("Entidades_SGBM.Ventas", b =>
                {
                    b.HasOne("Entidades_SGBM.Clientes", "Clientes")
                        .WithMany()
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Empleados", "Empleados")
                        .WithMany()
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entidades_SGBM.Estados", "Estados")
                        .WithMany()
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Clientes");

                    b.Navigation("Empleados");

                    b.Navigation("Estados");
                });
#pragma warning restore 612, 618
        }
    }
}
